appName: servicename
appReplicas: 2 
appImage: gcr.io/google-samples/microservices-demo/servicename
appVersion: v0.0.0
containerPort: 8080
containerEnvVars:
  - name: VAR_ONE 
    value: "valueone"
  - name: VAR_TWO 
    value: "valueteo"
servicePort: 8080
serviceType: LoadBalancer